drop table if exists videoxogo;
drop table if exists protagonista;
drop table if exists inimigo;
drop table if exists poder;
-- Tábóa poder
CREATE TABLE poder (
   id SERIAL PRIMARY KEY,
   nombre VARCHAR(100) NOT NULL,
   descripcion TEXT,
   nivel INT
);
-- Tábóa protagonista
CREATE TABLE protagonista (
   id SERIAL PRIMARY KEY,
   nombre VARCHAR(100) NOT NULL,
   edad INT,
   historia TEXT,
   poder_id INT,
   FOREIGN KEY (poder_id) REFERENCES poder(id)
);
-- Tábóa inimigo
CREATE TABLE inimigo (
   id SERIAL PRIMARY KEY,
   nombre VARCHAR(100) NOT NULL,
   poder VARCHAR(100),
   nivel INT
);
-- Tábóa videoxogo
CREATE TABLE videoxogo (
   id SERIAL PRIMARY KEY,
   titulo VARCHAR(100) NOT NULL,
   data_lanzamento DATE,
   desenvolvedor VARCHAR(100),
   plataforma VARCHAR(100),
   categoria VARCHAR(100),
   protagonista_id INT,
   inimigo_id INT,
   FOREIGN KEY (protagonista_id) REFERENCES protagonista(id),
   FOREIGN KEY (inimigo_id) REFERENCES inimigo(id)
);
INSERT INTO poder (nombre, descripcion, nivel) VALUES
('Espada Maestra', 'Una espada mítica con la capacidad de derrotar a seres oscuros.', 5),
('Bombas', 'Herramienta explosiva usada para abrir caminos o destruir enemigos.', 3),
('Invulnerabilidad', 'Una habilidad que hace al portador invulnerable a daños.', 5),
('Vuelo', 'Permite al protagonista volar durante un breve periodo de tiempo.', 4),
('Disparo de flechas de fuego', 'Flechas encantadas que arden al impactar, causando daño adicional.', 3),
('Teletransportación', 'Capacidad de viajar instantáneamente entre ubicaciones previamente descubiertas.', 4),
('Giro mortal', 'Una habilidad de ataque que permite al protagonista girar rápidamente, golpeando a los enemigos cercanos.', 4),
('Habilidad de robar alma', 'Permite al protagonista absorber las almas de los enemigos derrotados.', 5),
('Transformación', 'Habilidad de transformarse en otro ser, como un animal, para superar obstáculos.', 4),
('Curación', 'Permite restaurar la salud del protagonista con pociones o habilidades mágicas.', 4),
('Manipulación del tiempo', 'Capacidad de detener el tiempo durante un breve lapso para evitar ataques.', 5),
('Invocar bestias', 'Llamado de criaturas poderosas para que ayuden al protagonista en combate.', 4),
('Rayo de hielo', 'Emite un rayo de hielo que congela a los enemigos y bloquea caminos.', 3),
('Control de sombras', 'Habilidad para manipular sombras, creando criaturas oscuras para atacar a los enemigos.', 4),
('Super fuerza', 'El protagonista adquiere una fuerza sobrehumana para destruir objetos grandes o enemigos.', 5),
('Explosión de energía', 'Genera una explosión de energía que daña a todos los enemigos cercanos.', 4),
('Invocar criaturas', 'Permite invocar monstruos o entidades del juego para que ayuden al protagonista.', 5),
('Super agilidad', 'El protagonista puede moverse con gran rapidez, saltar más alto y esquivar ataques.', 3),
('Rayo láser', 'Disparo de energía concentrada en forma de rayo láser.', 3),
('Garras afiladas', 'Las manos del protagonista se transforman en garras afiladas para atacar enemigos.', 4),
('Maldición', 'Habilidad para maldecir a los enemigos, haciéndolos más débiles y vulnerables.', 4),
('Invocar tormenta', 'Permite al protagonista invocar una tormenta que afecta a sus enemigos.', 5),
('Dominar el fuego', 'El protagonista puede generar y controlar el fuego para atacar a sus enemigos.', 5),
('Reflejo rápido', 'Aumenta la capacidad del protagonista para esquivar ataques y reaccionar más rápido.', 3),
('Desmaterialización', 'Permite al protagonista desmaterializarse para atravesar obstáculos o atacar.', 5),
('Cambio de forma', 'El protagonista puede cambiar su forma para adaptarse a diferentes situaciones.', 4),
('Fase fantasmagórica', 'El protagonista se convierte en un ser etéreo para pasar a través de paredes y enemigos.', 4),
('Absorción de poder', 'El protagonista puede absorber energía de los enemigos derrotados y usarla para mejorar sus habilidades.', 5),
('Garras eléctricas', 'Las garras del protagonista emiten electricidad, causando daño adicional a los enemigos.', 4),
('Llamarada solar', 'Genera una explosión de energía solar que destruye enemigos a gran distancia.', 5),
('Rayo de luz', 'Un rayo de luz que puede atravesar obstáculos y enemigos, purificando todo a su paso.', 4),
('Acrobatismo extremo', 'El protagonista puede realizar saltos acrobáticos y balancearse en el entorno para llegar a lugares inaccesibles.', 3),
('Escudo de energía', 'Crea un escudo de energía que bloquea los ataques enemigos durante un tiempo.', 4),
('Habilidad de camuflaje', 'Permite al protagonista volverse invisible o casi invisible para moverse sin ser detectado.', 3),
('Corte mortal', 'El protagonista puede realizar un corte extremadamente rápido que daña gravemente al enemigo.', 5),
('Rayo venenoso', 'Emite un rayo venenoso que envenena a los enemigos y los debilita con el tiempo.', 4),
('Salto dimensional', 'Permite al protagonista saltar entre dimensiones o realidades paralelas.', 5),
('Manipulación de gravedad', 'El protagonista puede alterar la gravedad, haciendo más fáciles ciertos movimientos o ataques.', 5),
('Camuflaje ambiental', 'Permite al protagonista camuflarse con su entorno natural, volviéndose invisible a los enemigos.', 3),
('Invocar tormenta de arena', 'El protagonista puede invocar una tormenta de arena que dificulta la visión de los enemigos.', 4),
('Rugido de dragón', 'Un rugido capaz de aturdir a los enemigos y desintegrar obstáculos cercanos.', 5),
('Escudo de hielo', 'Crea un escudo de hielo que bloquea los ataques enemigos y congela a quienes lo tocan.', 4);
INSERT INTO protagonista (nombre, edad, historia, poder_id) VALUES
('Link', 16, 'Link es un joven héroe que lucha para salvar el reino de Hyrule de las fuerzas oscuras.', 1),
('Mario', 40, 'Mario es un fontanero que debe rescatar a la princesa Peach del malvado Bowser.', 4),
('Samus Aran', 30, 'Samus es una cazarrecompensas intergaláctica equipada con una armadura avanzada para luchar contra alienígenas.', 5),
('Sonic', 15, 'Sonic es un erizo superrápido que lucha contra el malvado Dr. Eggman para salvar el mundo.', 3),
('Kratos', 45, 'Kratos es un guerrero espartano que busca venganza contra los dioses del Olimpo.', 6),
('Lara Croft', 27, 'Lara es una arqueóloga que viaja por el mundo en busca de artefactos perdidos.', 7),
('Zelda', 18, 'Zelda es la princesa del reino de Hyrule y juega un papel crucial en la lucha contra Ganon.', 1),
('Master Chief', 40, 'Master Chief es un supersoldado que lucha contra los Covenant para salvar la humanidad.', 8),
('Mega Man', 10, 'Mega Man es un robot creado para combatir a los malvados robots que amenazan la paz mundial.', 9),
('Cloud Strife', 23, 'Cloud es un mercenario que se une a un grupo de rebeldes para derrotar a la corporación Shinra.', 10),
('Krillin', 35, 'Krillin es un guerrero Z que combate junto a Goku para proteger la Tierra.', 11),
('Ryu', 30, 'Ryu es un maestro del arte del combate que viaja por el mundo enfrentándose a poderosos rivales.', 12),
('Linkle', 18, 'Linkle es una joven aventurera que busca su destino como heroína en el mundo de Hyrule.', 1),
('Pit', 20, 'Pit es un ángel guerrero que lucha para defender el Reino de los Cielos contra las fuerzas del mal.', 13),
('Nathan Drake', 35, 'Nathan es un cazador de tesoros que viaja por el mundo en busca de artefactos históricos y enfrentándose a peligrosos enemigos.', 14);
INSERT INTO inimigo (nombre, poder, nivel) VALUES
('Ganon', 'Poder oscuro, magia oscura', 5),
('Bowser', 'Fuerza sobrehumana, piroquinesis', 4),
('Mother Brain', 'Control mental, rayos láser', 5),
('Dr. Eggman', 'Robots, armas avanzadas', 4),
('Ares', 'Fuerza sobrenatural, control de guerra', 5),
('Tomb Raider', 'Varia habilidad en combate, uso de trampas', 4),
('Dark Link', 'Sombra del héroe, maestría en espada', 5),
('Covenant', 'Tecnología avanzada, alienígenas', 4),
('Sigma', 'Transformaciones, control de robots', 5),
('Sephiroth', 'Control de la energía, espada larga', 5),
('Frieza', 'Super fuerza, habilidad para destruir planetas', 5),
('M. Bison', 'Poder psíquico, control mental', 4),
('Dark Pit', 'Control de las sombras, habilidad de volar', 4),
('Hades', 'Manipulación del inframundo, control de muertos', 5),
('Handsome Jack', 'Manipulación tecnológica, fuerza bruta', 4);
INSERT INTO videoxogo (titulo, data_lanzamento, desenvolvedor, plataforma, categoria, protagonista_id, inimigo_id) VALUES
('The Legend of Zelda: Ocarina of Time', '1998-11-21', 'Nintendo', 'Nintendo 64', 'Aventura', 1, 1),
('Super Mario Bros.', '1985-09-13', 'Nintendo', 'NES', 'Plataforma', 2, 2),
('Metroid', '1986-08-06', 'Nintendo', 'NES', 'Aventura', 3, 3),
('Sonic the Hedgehog', '1991-06-23', 'Sega', 'Sega Genesis', 'Plataforma', 4, 4),
('God of War', '2005-03-22', 'Santa Monica Studio', 'PS2', 'Acción/Aventura', 5, 5),
('Tomb Raider', '1996-10-25', 'Core Design', 'PC, PS1', 'Acción/Aventura', 6, 6),
('The Legend of Zelda: Breath of the Wild', '2017-03-03', 'Nintendo', 'Nintendo Switch', 'Aventura', 1, 1),
('Halo: Combat Evolved', '2001-11-15', 'Bungie', 'Xbox', 'FPS', 8, 8),
('Mega Man', '1987-12-17', 'Capcom', 'NES', 'Plataforma', 9, 9),
('Final Fantasy VII', '1997-01-29', 'Square', 'PlayStation', 'RPG', 10, 10),
('Dragon Ball Z: Budokai', '2002-11-12', 'Dimps', 'PS2', 'Lucha', 11, 11),
('Street Fighter II', '1991-03-30', 'Capcom', 'Arcade', 'Lucha', 12, 12),
('Hyrule Warriors', '2014-08-14', 'Omega Force', 'Wii U', 'Acción', 1, 1),
('Kid Icarus: Uprising', '2012-03-23', 'Project Sora', 'Nintendo 3DS', 'Aventura', 14, 14),
('Uncharted: Drake’s Fortune', '2007-11-19', 'Naughty Dog', 'PS3', 'Aventura', 15, 15),
('Super Mario 64', '1996-09-29', 'Nintendo', 'Nintendo 64', 'Plataforma', 2, 2),
('The Elder Scrolls V: Skyrim', '2011-11-11', 'Bethesda Game Studios', 'PC, PS3, Xbox 360', 'RPG', 15, 5),
('Dark Souls', '2011-09-22', 'FromSoftware', 'PS3, Xbox 360', 'Acción/RPG', 15, 5),
('Final Fantasy X', '2001-07-19', 'Square Enix', 'PS2', 'RPG', 10, 10),
('Overwatch', '2016-05-24', 'Blizzard Entertainment', 'PC, PS4, Xbox One', 'FPS', 8, 4),
('Red Dead Redemption 2', '2018-10-26', 'Rockstar Games', 'PS4, Xbox One', 'Aventura', 15, 8),
('Assassin’s Creed', '2007-11-13', 'Ubisoft', 'PS3, Xbox 360', 'Acción/Aventura', 15, 5),
('Castlevania: Symphony of the Night', '1997-10-02', 'Konami', 'PS1', 'Acción', 9, 3),
('The Witcher 3: Wild Hunt', '2015-05-19', 'CD Projekt Red', 'PC, PS4, Xbox One', 'RPG', 15, 4),
('Portal', '2007-10-10', 'Valve', 'PC, PS3', 'Puzle', 12, 14),
('Super Smash Bros. Ultimate', '2018-12-07', 'Nintendo', 'Nintendo Switch', 'Lucha', 1, 8),
('Bioshock', '2007-08-21', 'Irrational Games', 'PC, Xbox 360', 'FPS', 15, 5),
('Minecraft', '2011-11-18', 'Mojang', 'PC, PS3, Xbox 360', 'Aventura', 15, 4),
('Resident Evil 4', '2005-01-11', 'Capcom', 'GameCube', 'Acción/Horror', 15, 5),
('The Last of Us', '2013-06-14', 'Naughty Dog', 'PS3', 'Aventura', 15, 5),
('Bloodborne', '2015-03-24', 'FromSoftware', 'PS4', 'Acción/RPG', 15, 5),
('The Legend of Zelda: The Wind Waker', '2002-12-13', 'Nintendo', 'GameCube', 'Aventura', 1, 1),
('Doom', '1993-12-10', 'id Software', 'PC', 'FPS', 8, 4),
('Metal Gear Solid', '1998-10-21', 'Konami', 'PS1', 'Acción', 15, 5),
('The Legend of Zelda: A Link to the Past', '1991-11-21', 'Nintendo', 'SNES', 'Aventura', 1, 5),
('Final Fantasy XII', '2006-03-16', 'Square Enix', 'PS2', 'RPG', 10, 10),
('Persona 5', '2016-09-15', 'Atlus', 'PS4', 'RPG', 10, 5),
('Tales of Vesperia', '2008-08-07', 'Namco Bandai', 'Xbox 360', 'RPG', 10, 5);
